services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: thomas
      POSTGRES_PASSWORD: ${SET_RAILS_DATABASE_PASSWORD_DEVELOPMENT}
      POSTGRES_DB: set_rails_development
    ports:
      - 5432:5432
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: 
      - .env
    volumes:
      - .:/set-rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_USERNAME=thomas
      - DB_PASSWORD=${SET_RAILS_DATABASE_PASSWORD_DEVELOPMENT}
      - DB_HOST=db
      - RAILS_ENV=development
volumes:
  postgres_data: